In [1]:
import numpy as np
import pylab as pp
import pandas as pd
import os

pp.style.use("bmh")

os.chdir("D:\Stocks\PersianCal")
import PersianCal

In [2]:
filename = "SekeJadid_D_COM - Copy.csv"
loc = "D:\Stocks\Data"

os.chdir(loc)

# Loading in the Data
df = pd.read_csv(filename, delimiter=",")

In [3]:
## Datetime conversion
df['<DTYYYYMMDD>'] = pd.to_datetime(df['<DTYYYYMMDD>'], format='%Y%m%d')

# Dropping any NaNs
df.dropna(inplace=True)

df.rename(columns={"<DTYYYYMMDD>": "Date"}, inplace=True)

In [4]:
d = []
for i in range(len(df["Date"])):
    d.append(PersianCal.Gregorian(str(df["Date"][i])[0:10]).persian_string()) #Tabdil tarikh be Irani

In [5]:
for i in range(len(df["Date"])):
    df["Date"] = df["Date"].replace(df["Date"][i], d[i])

In [6]:
date_list = []
for date in df["Date"]:
    date_list.append(date[:7])
    
Dates = df["Date"].tolist() #kole tarikh ha
myDates = list(dict.fromkeys(date_list)) #Eshterake Tatikh ha

In [7]:
ext = np.zeros((len(myDates), 2)) #[[max], [min]]
ind = np.zeros((len(myDates), 1)).tolist()

#first indicator
for date in Dates:
    if (date[:7] in myDates[0]):
        ind1 = Dates.index(date) #یافتن مکان آخرین روز ماه

ind[0] = ind1

# First max and min:

In [8]:
a = [[], [], [], []]
names = ["<Open>", "<High>", "<Low>", "<Close>"]

for i in range(4):
    for j in names:
        a[i] = df[j][0+1:ind1+1].tolist()

ext[0][0] = max(max(a))
ext[0][1] = min(min(a))

# Calculating all of the extremums:

In [9]:
for i in range(1, len(myDates)):
    for date in Dates:
        if (date[:7] in myDates[i]):
            ind1 = Dates.index(date)
    ind[i] = ind1
    a = [[], [], [], []]
    for ii in range(4):
        for j in names:
            a[ii] = df[j][ind[i-1]+1:ind[i]+1].tolist()
    ext[i][0] = max(max(a))
    ext[i][1] = min(min(a))

In [10]:
Data = {"Date": myDates,
        "Max": ext[:, 0],
        "Min": ext[:, 1]}
DataF = pd.DataFrame(Data)
DataF.set_index('Date', inplace=True)

In [12]:
DataF.to_csv("output.csv")

In [13]:
# %matplotlib notebook
# import pylab as pp

# pp.plot(DataF["Date"], DataF["Max"], color='skyblue', label = "Max")
# pp.plot(DataF["Date"], DataF["Min"], color='red', label = "Min")
# pp.legend();

In [16]:
d = [[], [], [], []]

for i in range(4):
    for name in names:
        d[i] = df[name].tolist()

In [39]:
# for j in range(len(ext)):
#     for i in range(4):
#         print(d[i].index(ext[j][0]))

[df[names[0]][ind[2]+1:ind[3]+1] == 2160000].index

In [54]:
import io
import urllib.request
import requests
url = "https://www.tgju.org/profile/price_dollar_rl/history"
# r = requests.get(url, allow_redirects=True).content
calls_df = pd.read_html(url, encoding = 'utf-8')

In [63]:
dd = pd.DataFrame(calls_df[0])

In [67]:
dd

,بازگشایی؟,کمترین؟,بیشترین؟,پایانی؟,میزان تغییر,درصد تغییر,تاریخ / میلادی,تاریخ / شمسی
0,222520,222410,225520,225520,3110,1.4%,2020/07/12,1399/04/22
1,221930,220410,222520,222410,390,0.18%,2020/07/11,1399/04/21
2,221940,221910,222020,222020,0,-,2020/07/09,1399/04/19
3,217460,217410,222020,222020,4500,2.07%,2020/07/08,1399/04/18
4,218450,216410,218520,217520,1000,0.46%,2020/07/07,1399/04/17
5,216460,216410,218520,218520,2050,0.95%,2020/07/06,1399/04/16
6,209020,208910,216520,216470,7560,3.62%,2020/07/05,1399/04/15
7,189470,189410,209020,208910,19390,10.23%,2020/07/04,1399/04/14
8,189520,189410,189520,189520,80,0.04%,2020/07/02,1399/04/12
9,189850,189410,189920,189440,480,0.25%,2020/07/01,1399/04/11
10,190440,189810,190520,189920,600,0.32%,2020/06/30,1399/04/10
11,190520,190410,190520,190520,90,0.05%,2020/06/29,1399/04/9
12,188520,188410,190520,190430,2020,1.07%,2020/06/28,1399/04/8
13,188520,188410,188520,188410,20,0.01%,2020/06/27,1399/04/7
14,191510,188410,191620,188430,4590,2.44%,2020/06/25,1399/04/5
15,195890,192910,195970,193020,2950,1.53%,2020/06/24,1399/04/4
16,187930,187910,195970,195970,7950,4.23%,2020/06/23,1399/04/3
17,187910,187910,188020,188020,0,-,2020/06/22,1399/04/2
18,185950,185910,188020,188020,2000,1.08%,2020/06/21,1399/04/1
19,183490,183410,186020,186020,2520,1.37%,2020/06/20,1399/03/31
20,183500,183410,183610,183500,1400,0.77%,2020/06/18,1399/03/29
21,178850,178800,182110,182100,3300,1.85%,2020/06/16,1399/03/27
22,177530,177500,178910,178800,1200,0.68%,2020/06/15,1399/03/26
23,177600,177500,177610,177600,40,0.02%,2020/06/14,1399/03/25
24,177550,177500,177610,177560,60,0.03%,2020/06/13,1399/03/24
25,177500,177500,177610,177500,5000,2.9%,2020/06/11,1399/03/22
26,169350,169300,172610,172500,3200,1.89%,2020/06/10,1399/03/21
27,169360,169300,169410,169300,90,0.05%,2020/06/09,1399/03/20
28,169300,169300,169410,169390,50,0.03%,2020/06/08,1399/03/19
29,169800,169300,169800,169340,50,0.03%,2020/06/07,1399/03/18